image: node:14.15.1

variables:
  PUBLIC_URL: "/kit-cv"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - CI=true npm run app:build
    - rm -rf public
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
